---
name: "Muhammad Aswan **Syahputra**"
position: "Data Analyst \u00B7 Sensometrics Specialist"
aboutme: "I would like to recognize myself as a Food Data Scientist. I have an expertise in Sensory Science with a Food Technology background, a passion in data analysis and visualisation, an eagerness in R statistical programming, and a hobby in developing analytical web application."
address: "Puri Cipageran Indah I Blok A No 191, Kota Cimahi, Jawa Barat, Indonesia"
phone: (+62) 822 3465 3816
email: muhammadaswansyahputra@gmail.com
github: aswansyahputra
linkedin: aswansyahputra
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "414141"
output: 
  vitae::awesomecv:
    keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Work

```{r}
work <- read.csv("../data/work.csv")

work %>% 
  detailed_entries(
    what = what,
    when = when,
    with = with,
    where = where,
    why = why
  )
```

# Education

```{r}
education <- read.csv("../data/education.csv")

education %>% 
  detailed_entries(
    what = what,
    when = when,
    with = with,
    where = where,
    why = why
  )
```

# External Activity
```{r}
activity <- read.csv("../data/activity.csv") %>% 
  slice(c(-4, -5))

activity %>%
  detailed_entries(
    what = what,
    when = when,
    with = with,
    where = where,
    why = why
  )
```

# Research

```{r}
research <- read.csv("../data/research.csv")

research %>% 
  detailed_entries(
    what = event,
    when = when,
    with = topic,
    where = where,
    why = why
  )
```

# Delivered Presentation and Training

```{r}
presentation <- read.csv("../data/presentation.csv")

presentation %>%
  detailed_entries(
    what = event,
    when = when,
    with = title,
    where = where,
    why = content
  )
```

# Developed Software

```{r}
project <- read.csv("../data/project.csv")

project %>% 
  brief_entries(
    what = what,
    when = type,
    .protect = FALSE
  )
```
